# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d78d84a2f74ce5617952aeef6e6575650aec74c76d86c1f5843e5113df3282d36d76a8d14bf4c894c357f1cbb254bd213acb636fe010c966c1eb53315f94efc

test:
  secret_key_base: ed3195ff49ae69c9fd37d441a4c49a542c6caf81b5da1ccb26bc4ca1bc5843c7cf94b4e94e4cd45be3fc0f5d386436e084afb5696e9dc2b178494759ba2618b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
